version: '3.8'
services:
  golang-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  nginx:
    image: nginx:1.25.4
    restart: always
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx-golang.crt:/etc/nginx/ssl/nginx-golang.crt
      - ./nginx/nginx-golang.key:/etc/nginx/ssl/nginx-golang.key

    ports:
      - "80:80"
    depends_on:
      - golang-app
